#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mojolingo-misc', path: 'mojolingo-misc'
cookbook 'rbenv', path: 'rbenv'

cookbook 'apt'
cookbook 'asterisk', git: 'git://github.com/mojolingo/asterisk-cookbook.git'
cookbook 'freeswitch', git: 'https://github.com/mojolingo/freeswitch-cookbook.git'
cookbook 'java'
cookbook 'jmxsh', git: 'https://bitbucket.org/voxeolabs/jmxsh-chef'
cookbook 'prism', git: 'https://bitbucket.org/voxeolabs/prism-chef.git'
cookbook 'rayo', git: 'https://bitbucket.org/voxeolabs/rayo-chef.git'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'chef-solo-search', git: 'https://github.com/edelight/chef-solo-search.git'
cookbook 'yum'
