#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'mojolingo-misc', path: 'mojolingo-misc'
cookbook 'sipp', path: 'sipp'
cookbook 'wav2rtp', path: 'wav2rtp'

cookbook 'apt'
cookbook 'asterisk', git: 'git://github.com/mojolingo/asterisk-cookbook.git'
cookbook 'freeswitch', git: 'https://github.com/mojolingo/freeswitch-cookbook.git', ref: 'feature/rayo'
cookbook 'java'
cookbook 'jmxsh', git: 'https://bitbucket.org/voxeolabs/jmxsh-chef'
cookbook 'prism', git: 'https://bitbucket.org/voxeolabs/prism-chef.git'
cookbook 'rayo', git: 'https://bitbucket.org/voxeolabs/rayo-chef.git'
cookbook 'rbenv', git: 'https://github.com/fnichol/chef-rbenv.git', ref: 'v0.7.2'
cookbook 'ruby_build', git: 'https://github.com/fnichol/chef-ruby_build.git'
cookbook 'chef-solo-search', git: 'https://github.com/edelight/chef-solo-search.git'
cookbook 'lumenvox', git: 'https://github.com/mojolingo/lumenvox-chef.git'
cookbook 'yum'
cookbook 'sudo'
